from observer_worlds.analysis.plots import plot_lifetimes, plot_area_vs_time
from observer_worlds.analysis.summarize_results import (
    RunSummary,
    load_run,
    load_runs,
    plot_baseline_comparison,
    plot_observer_score_histogram,
    plot_score_vs_age,
    summary_table,
    write_summary_md,
)
from observer_worlds.analysis.videos import write_projected_gif
from observer_worlds.analysis.m4b_stats import (
    COMPARISON_PAIRS,
    HEADLINE_METRICS,
    PairedDifference,
    compute_all_paired_differences,
    compute_paired_difference,
    render_stats_summary_md,
    stats_summary_dict,
    win_rate_random_candidate,
    write_stats_summary_json,
)
from observer_worlds.analysis.m4b_plots import (
    CONDITION_COLORS,
    plot_activity_traces,
    plot_bootstrap_ci_paired_differences,
    plot_condition_boxplot,
    plot_condition_violin,
    plot_metric_breakdown_best_candidates,
    plot_paired_lines,
    plot_scatter_score_vs_tracks,
    plot_track_count_by_condition,
    write_all_m4b_plots,
    write_top_candidate_videos,
)
from observer_worlds.analysis.m5_plots import (
    INTERVENTION_COLORS,
    plot_aggregate_divergence,
    plot_intervention_heatmap,
    plot_intervention_summary_bars,
    plot_per_candidate_divergence,
    plot_resilience_curves,
    write_all_m5_plots,
)
from observer_worlds.analysis.m6_plots import (
    PERTURBATION_COLORS,
    CONDITION_COLORS_M6,
    plot_aggregate_divergence_per_perturbation,
    plot_hce_boxplot_by_condition,
    plot_hce_coherent_vs_shuffled_paired,
    plot_hce_distribution,
    plot_hce_vs_visible_scatter,
    write_all_m6_plots,
)
from observer_worlds.analysis.m6b_plots import (
    INTERVENTION_PALETTE,
    write_all_m6b_plots,
)
from observer_worlds.analysis.m6b_stats import (
    aggregate_by_condition_intervention_horizon,
    compare_paired,
    grouped_bootstrap_mean_ci,
    m6b_full_summary,
    render_m6b_summary_md,
    sign_test_p,
    standard_paired_comparisons,
)

__all__ = [
    "plot_lifetimes",
    "plot_area_vs_time",
    "write_projected_gif",
    "RunSummary",
    "load_run",
    "load_runs",
    "plot_observer_score_histogram",
    "plot_score_vs_age",
    "plot_baseline_comparison",
    "summary_table",
    "write_summary_md",
    "PairedDifference",
    "compute_paired_difference",
    "compute_all_paired_differences",
    "win_rate_random_candidate",
    "stats_summary_dict",
    "write_stats_summary_json",
    "render_stats_summary_md",
    "COMPARISON_PAIRS",
    "HEADLINE_METRICS",
    # M4B plots
    "CONDITION_COLORS",
    "plot_condition_boxplot",
    "plot_condition_violin",
    "plot_paired_lines",
    "plot_scatter_score_vs_tracks",
    "plot_track_count_by_condition",
    "plot_metric_breakdown_best_candidates",
    "plot_bootstrap_ci_paired_differences",
    "plot_activity_traces",
    "write_top_candidate_videos",
    "write_all_m4b_plots",
    # M5 plots
    "INTERVENTION_COLORS",
    "plot_per_candidate_divergence",
    "plot_resilience_curves",
    "plot_aggregate_divergence",
    "plot_intervention_heatmap",
    "plot_intervention_summary_bars",
    "write_all_m5_plots",
    # M6 plots
    "PERTURBATION_COLORS",
    "CONDITION_COLORS_M6",
    "plot_aggregate_divergence_per_perturbation",
    "plot_hce_boxplot_by_condition",
    "plot_hce_coherent_vs_shuffled_paired",
    "plot_hce_distribution",
    "plot_hce_vs_visible_scatter",
    "write_all_m6_plots",
]
